name: Terraform

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Choose an environment to deploy to"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  terraform:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grab backend
        working-directory: terraform
        run: |
          echo ${{ secrets.TF_BACKEND }} >> backend.vars

      - name: Init
        uses: docker://hashicorp/terraform:1.9.5
        with:
          entrypoint: terraform
          args: -chdir=terraform init -backend-config=backend.vars

      - name: Plan
        uses: docker://hashicorp/terraform:1.9.5
        env:
          TF_VAR_azure_client_id: ${{ secrets.TF_AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.TF_AZURE_CLIENT_SECRET }}
        with:
          entrypoint: terraform
          args: -chdir=terraform plan

      - name: Apply
        uses: docker://hashicorp/terraform:1.9.5
        env:
          TF_VAR_azure_client_id: ${{ secrets.TF_AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.TF_AZURE_CLIENT_SECRET }}
        with:
          entrypoint: terraform
          args: -chdir=terraform apply
