name: Terraform

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Choose an environment to deploy to"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  terraform:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.TF_AZURE_CREDENTIALS }}

      - name: Grab backend
        working-directory: terraform
        run: |
          echo '${{ secrets.TF_BACKEND }}' >> backend.vars

      - name: Unlock state container
        uses: azure/cli@v2
        with:
          azcliversion: 2.64.0
          inlineScript: |
            az storage account update \
              --resource-group "${{ secrets.TF_STATE_RG }}" \
              --name "${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}" \
              --default-action Allow

            sleep 10

            until [[
              $ACTION == 'Allow'
            ]]
            do
              ACTION=$(az storage account show \
                --resource-group "${{ secrets.TF_STATE_RG }}" \
                --name "${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}" \
                --query networkRuleSet.defaultAction \
                --output tsv)

              sleep 10
            done

      - name: Init
        uses: docker://hashicorp/terraform:1.9.5
        with:
          entrypoint: terraform
          args: -chdir=terraform init -backend-config=backend.vars -input=false

      - name: Plan
        uses: docker://hashicorp/terraform:1.9.5
        env:
          TF_VAR_azure_client_id: ${{ secrets.TF_AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.TF_AZURE_CLIENT_SECRET }}
        with:
          entrypoint: terraform
          args: -chdir=terraform plan -out=tfplan -input=false

      - name: Apply
        uses: docker://hashicorp/terraform:1.9.5
        env:
          TF_VAR_azure_client_id: ${{ secrets.TF_AZURE_CLIENT_ID }}
          TF_VAR_azure_client_secret: ${{ secrets.TF_AZURE_CLIENT_SECRET }}
        with:
          entrypoint: terraform
          args: -chdir=terraform apply -input=false tfplan

      - name: Lock state container
        uses: azure/cli@v2
        with:
          azcliversion: 2.64.0
          inlineScript: |
            az storage account update \
              --resource-group "${{ secrets.TF_STATE_RG }}" \
              --name "${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}" \
              --default-action Deny

            sleep 10

            until [[
              $ACTION == 'Deny'
              ]]
              do
              ACTION=$(az storage account show \
                --resource-group "${{ secrets.TF_STATE_RG }}" \
                --name "${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}" \
                --query networkRuleSet.defaultAction \
                --output tsv)
              sleep 10
            done
